// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: lake_service.proto

package sdb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LakeClient is the client API for Lake service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LakeClient interface {
	Start(ctx context.Context, in *StartTransactionRequest, opts ...grpc.CallOption) (*StartTransactionResponse, error)
	AllocateXid(ctx context.Context, in *AllocateXidRequest, opts ...grpc.CallOption) (*AllocateXidResponse, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*AbortResponse, error)
	PrepareInsertFiles(ctx context.Context, in *PrepareInsertFilesRequest, opts ...grpc.CallOption) (*PrepareInsertFilesResponse, error)
	DeleteFiles(ctx context.Context, in *DeleteFilesRequest, opts ...grpc.CallOption) (*DeleteFilesResponse, error)
	GetFileList(ctx context.Context, in *GetFilesRequest, opts ...grpc.CallOption) (*GetFilesResponse, error)
}

type lakeClient struct {
	cc grpc.ClientConnInterface
}

func NewLakeClient(cc grpc.ClientConnInterface) LakeClient {
	return &lakeClient{cc}
}

func (c *lakeClient) Start(ctx context.Context, in *StartTransactionRequest, opts ...grpc.CallOption) (*StartTransactionResponse, error) {
	out := new(StartTransactionResponse)
	err := c.cc.Invoke(ctx, "/sdb.Lake/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lakeClient) AllocateXid(ctx context.Context, in *AllocateXidRequest, opts ...grpc.CallOption) (*AllocateXidResponse, error) {
	out := new(AllocateXidResponse)
	err := c.cc.Invoke(ctx, "/sdb.Lake/AllocateXid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lakeClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, "/sdb.Lake/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lakeClient) Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*AbortResponse, error) {
	out := new(AbortResponse)
	err := c.cc.Invoke(ctx, "/sdb.Lake/Abort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lakeClient) PrepareInsertFiles(ctx context.Context, in *PrepareInsertFilesRequest, opts ...grpc.CallOption) (*PrepareInsertFilesResponse, error) {
	out := new(PrepareInsertFilesResponse)
	err := c.cc.Invoke(ctx, "/sdb.Lake/PrepareInsertFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lakeClient) DeleteFiles(ctx context.Context, in *DeleteFilesRequest, opts ...grpc.CallOption) (*DeleteFilesResponse, error) {
	out := new(DeleteFilesResponse)
	err := c.cc.Invoke(ctx, "/sdb.Lake/DeleteFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lakeClient) GetFileList(ctx context.Context, in *GetFilesRequest, opts ...grpc.CallOption) (*GetFilesResponse, error) {
	out := new(GetFilesResponse)
	err := c.cc.Invoke(ctx, "/sdb.Lake/GetFileList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LakeServer is the server API for Lake service.
// All implementations must embed UnimplementedLakeServer
// for forward compatibility
type LakeServer interface {
	Start(context.Context, *StartTransactionRequest) (*StartTransactionResponse, error)
	AllocateXid(context.Context, *AllocateXidRequest) (*AllocateXidResponse, error)
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	Abort(context.Context, *AbortRequest) (*AbortResponse, error)
	PrepareInsertFiles(context.Context, *PrepareInsertFilesRequest) (*PrepareInsertFilesResponse, error)
	DeleteFiles(context.Context, *DeleteFilesRequest) (*DeleteFilesResponse, error)
	GetFileList(context.Context, *GetFilesRequest) (*GetFilesResponse, error)
	mustEmbedUnimplementedLakeServer()
}

// UnimplementedLakeServer must be embedded to have forward compatible implementations.
type UnimplementedLakeServer struct {
}

func (UnimplementedLakeServer) Start(context.Context, *StartTransactionRequest) (*StartTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedLakeServer) AllocateXid(context.Context, *AllocateXidRequest) (*AllocateXidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocateXid not implemented")
}
func (UnimplementedLakeServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedLakeServer) Abort(context.Context, *AbortRequest) (*AbortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Abort not implemented")
}
func (UnimplementedLakeServer) PrepareInsertFiles(context.Context, *PrepareInsertFilesRequest) (*PrepareInsertFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareInsertFiles not implemented")
}
func (UnimplementedLakeServer) DeleteFiles(context.Context, *DeleteFilesRequest) (*DeleteFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFiles not implemented")
}
func (UnimplementedLakeServer) GetFileList(context.Context, *GetFilesRequest) (*GetFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileList not implemented")
}
func (UnimplementedLakeServer) mustEmbedUnimplementedLakeServer() {}

// UnsafeLakeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LakeServer will
// result in compilation errors.
type UnsafeLakeServer interface {
	mustEmbedUnimplementedLakeServer()
}

func RegisterLakeServer(s grpc.ServiceRegistrar, srv LakeServer) {
	s.RegisterService(&Lake_ServiceDesc, srv)
}

func _Lake_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LakeServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdb.Lake/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LakeServer).Start(ctx, req.(*StartTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lake_AllocateXid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateXidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LakeServer).AllocateXid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdb.Lake/AllocateXid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LakeServer).AllocateXid(ctx, req.(*AllocateXidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lake_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LakeServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdb.Lake/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LakeServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lake_Abort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LakeServer).Abort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdb.Lake/Abort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LakeServer).Abort(ctx, req.(*AbortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lake_PrepareInsertFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareInsertFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LakeServer).PrepareInsertFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdb.Lake/PrepareInsertFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LakeServer).PrepareInsertFiles(ctx, req.(*PrepareInsertFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lake_DeleteFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LakeServer).DeleteFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdb.Lake/DeleteFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LakeServer).DeleteFiles(ctx, req.(*DeleteFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lake_GetFileList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LakeServer).GetFileList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdb.Lake/GetFileList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LakeServer).GetFileList(ctx, req.(*GetFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Lake_ServiceDesc is the grpc.ServiceDesc for Lake service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lake_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sdb.Lake",
	HandlerType: (*LakeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Lake_Start_Handler,
		},
		{
			MethodName: "AllocateXid",
			Handler:    _Lake_AllocateXid_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Lake_Commit_Handler,
		},
		{
			MethodName: "Abort",
			Handler:    _Lake_Abort_Handler,
		},
		{
			MethodName: "PrepareInsertFiles",
			Handler:    _Lake_PrepareInsertFiles_Handler,
		},
		{
			MethodName: "DeleteFiles",
			Handler:    _Lake_DeleteFiles_Handler,
		},
		{
			MethodName: "GetFileList",
			Handler:    _Lake_GetFileList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lake_service.proto",
}
