// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.6
// source: workerinfo.proto

package sdb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr  string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Id    int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`       // global id
	Segid int32  `protobuf:"varint,3,opt,name=segid,proto3" json:"segid,omitempty"` // loacl id for query
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workerinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_workerinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_workerinfo_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *WorkerInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WorkerInfo) GetSegid() int32 {
	if x != nil {
		return x.Segid
	}
	return 0
}

type WorkerDetailInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseInfo *WorkerInfo `protobuf:"bytes,1,opt,name=base_info,json=baseInfo,proto3" json:"base_info,omitempty"`
}

func (x *WorkerDetailInfo) Reset() {
	*x = WorkerDetailInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workerinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerDetailInfo) ProtoMessage() {}

func (x *WorkerDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_workerinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerDetailInfo.ProtoReflect.Descriptor instead.
func (*WorkerDetailInfo) Descriptor() ([]byte, []int) {
	return file_workerinfo_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerDetailInfo) GetBaseInfo() *WorkerInfo {
	if x != nil {
		return x.BaseInfo
	}
	return nil
}

type WorkerSliceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerInfo *WorkerInfo `protobuf:"bytes,1,opt,name=worker_info,json=workerInfo,proto3" json:"worker_info,omitempty"`
	Sliceid    int32       `protobuf:"varint,2,opt,name=sliceid,proto3" json:"sliceid,omitempty"`
}

func (x *WorkerSliceInfo) Reset() {
	*x = WorkerSliceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workerinfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerSliceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerSliceInfo) ProtoMessage() {}

func (x *WorkerSliceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_workerinfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerSliceInfo.ProtoReflect.Descriptor instead.
func (*WorkerSliceInfo) Descriptor() ([]byte, []int) {
	return file_workerinfo_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerSliceInfo) GetWorkerInfo() *WorkerInfo {
	if x != nil {
		return x.WorkerInfo
	}
	return nil
}

func (x *WorkerSliceInfo) GetSliceid() int32 {
	if x != nil {
		return x.Sliceid
	}
	return 0
}

var File_workerinfo_proto protoreflect.FileDescriptor

var file_workerinfo_proto_rawDesc = []byte{
	0x0a, 0x10, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x73, 0x64, 0x62, 0x22, 0x46, 0x0a, 0x0a, 0x57, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x67,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x65, 0x67, 0x69, 0x64, 0x22,
	0x40, 0x0a, 0x10, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x64, 0x62, 0x2e, 0x57, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x5d, 0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x6c, 0x69, 0x63, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x30, 0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x64, 0x62, 0x2e,
	0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x69, 0x64,
	0x42, 0x0a, 0x5a, 0x05, 0x2e, 0x2f, 0x73, 0x64, 0x62, 0x80, 0x01, 0x01, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_workerinfo_proto_rawDescOnce sync.Once
	file_workerinfo_proto_rawDescData = file_workerinfo_proto_rawDesc
)

func file_workerinfo_proto_rawDescGZIP() []byte {
	file_workerinfo_proto_rawDescOnce.Do(func() {
		file_workerinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_workerinfo_proto_rawDescData)
	})
	return file_workerinfo_proto_rawDescData
}

var file_workerinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_workerinfo_proto_goTypes = []interface{}{
	(*WorkerInfo)(nil),       // 0: sdb.WorkerInfo
	(*WorkerDetailInfo)(nil), // 1: sdb.WorkerDetailInfo
	(*WorkerSliceInfo)(nil),  // 2: sdb.WorkerSliceInfo
}
var file_workerinfo_proto_depIdxs = []int32{
	0, // 0: sdb.WorkerDetailInfo.base_info:type_name -> sdb.WorkerInfo
	0, // 1: sdb.WorkerSliceInfo.worker_info:type_name -> sdb.WorkerInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_workerinfo_proto_init() }
func file_workerinfo_proto_init() {
	if File_workerinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_workerinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workerinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerDetailInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workerinfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerSliceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_workerinfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workerinfo_proto_goTypes,
		DependencyIndexes: file_workerinfo_proto_depIdxs,
		MessageInfos:      file_workerinfo_proto_msgTypes,
	}.Build()
	File_workerinfo_proto = out.File
	file_workerinfo_proto_rawDesc = nil
	file_workerinfo_proto_goTypes = nil
	file_workerinfo_proto_depIdxs = nil
}
